version: '3'
services:
  shefrunner:
    build:
      context: ./
      target: dev
    container_name: shefRunner
    labels:
      - "shef-shefRunner=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
    ports:
      - "11044:11044"
    environment:
      - NODE_ENV=development
      - HOST_IP=192.168.1.44
      - MASTER_HOST=192.168.1.44
      - LOG_LEVEL=debug
      - TZ=Europe/Istanbul
    restart: always