version: '3'
services:
  bouter:
    build:
      context: ./
      target: dev
    container_name: bouter
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
    environment:
      - NODE_ENV=development
      - HOST_IP=192.168.1.44
      - MASTER_HOST=192.168.1.44
      - LOG_LEVEL=debug
      - TZ=Europe/Istanbul
    restart: always